cyclestreets/android

cyclestreets.vNext/build.gradle
cyclestreets.vNext/src/main/java/net/cyclestreets/CycleStreetsApp.java

Updated ACRA to version 4.8.5
Removed deprecated "formkey" parameter

Fixed issue #118

---

config.properties
libraries/cyclestreets-view/build.gradle
libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/LiveRideState.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/PebbleNotifier.java

Update to PebbleKit sdk 3

---

build.gradle
gradle/lint.xml
libraries/cyclestreets-core/build.gradle
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/ApiClient.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/GeoPlaces.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/Photo.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/Photos.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/UserJourney.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/UserJourneys.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/RetrofitApiClient.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/V1Api.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/V2Api.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/dto/GeoPlaceDto.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/dto/GeoPlacesDto.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/dto/UserJourneysDto.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/geojson/AbstractObjectFactory.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/geojson/PhotosFactory.java
libraries/cyclestreets-core/src/test/java/net/cyclestreets/api/client/RetrofitApiClientIntegrationTest.java
libraries/cyclestreets-core/src/test/java/net/cyclestreets/api/client/RetrofitApiClientTest.java
libraries/cyclestreets-core/src/test/resources/__files/geocoder.xml
libraries/cyclestreets-core/src/test/resources/__files/journeys.json
libraries/cyclestreets-core/src/test/resources/__files/photos.json

Follow on from #134.  Contributes to the completion of #133.

Migrate `getPhotos()`, `getUserJourneys()`, and `geoCoder()` APIs to Retrofit

---

libraries/cyclestreets-core/build.gradle
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/ApiClient.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/Upload.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/RetrofitApiClient.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/V2Api.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/dto/UploadPhotoResponseDto.java
libraries/cyclestreets-core/src/test/java/net/cyclestreets/api/client/RetrofitApiClientIntegrationTest.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/PhotoUploadActivity.java

Migrate uploadPhoto() API to Retrofit

---

libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/ApiClient.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/Feedback.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/Registration.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/Result.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/RetrofitApiClient.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/dto/SendFeedbackResponseDto.java
libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/dto/UserCreateResponseDto.java
libraries/cyclestreets-core/src/test/java/net/cyclestreets/api/client/RetrofitApiClientIntegrationTest.java
libraries/cyclestreets-core/src/test/java/net/cyclestreets/api/client/RetrofitApiClientTest.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/AccountDetailsActivity.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/FeedbackActivity.java
libraries/cyclestreets-view/src/main/res/values/strings.xml

Send route feedback asynchronously

---

cyclestreets.vNext/src/main/res/values-ru/strings.xml
libraries/cyclestreets-core/src/main/res/values-ru/arrays.xml
libraries/cyclestreets-core/src/main/res/values-ru/strings.xml
libraries/cyclestreets-fragments/src/main/res/values-ru/strings.xml
libraries/cyclestreets-track/src/main/res/values-ru/strings.xml
libraries/cyclestreets-view/src/main/res/values-ru/strings.xml

I've added russian translation of listed files. Please review and add my PR

Russian translation

---

cyclestreets.vNext/src/main/res/values-it/strings.xml
libraries/cyclestreets-core/src/main/res/values-it/arrays.xml
libraries/cyclestreets-core/src/main/res/values-it/strings.xml
libraries/cyclestreets-fragments/src/main/res/values-it/strings.xml
libraries/cyclestreets-track/src/main/res/values-it/strings.xml
libraries/cyclestreets-view/src/main/res/values-it/strings.xml
libraries/cyclestreets-view/src/main/res/values-pt/strings.xml

Italian translation added #171

---

cyclestreets.vNext/src/main/res/values-fr/strings.xml
libraries/cyclestreets-core/src/main/res/values-fr/arrays.xml
libraries/cyclestreets-core/src/main/res/values-fr/strings.xml
libraries/cyclestreets-fragments/src/main/res/values-fr/strings.xml
libraries/cyclestreets-track/src/main/res/values-fr/strings.xml
libraries/cyclestreets-view/src/main/res/values-fr/strings.xml

Addition of a French translation

Add French translation

---

.travis.yml
build.gradle
config.properties
libraries/cyclestreets-fragments/build.gradle
libraries/cyclestreets-view/build.gradle
libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/PlaceAutoCompleteTextView.java

Bump minSdkVersion to 17 (Android 4.2 Jelly Bean MR1)

---

.travis.yml
cyclestreets.app/build.gradle
libraries/cyclestreets-core/build.gradle
libraries/cyclestreets-view/build.gradle

A few upgrades to dependencies that the linter pointed out to me.  Nice and simple.

Dependency upgrades

---

build.gradle
gradle/lint.xml

Follows on from #202.
@jezhiggins are you happy with this change?

Reintroduce abortOnError for linting, make specific exclusions instead

---

.travis.yml
cyclestreets.app/version.properties

Fix beta publishing

---

cyclestreets.app/src/main/assets/whatsnew.html
libraries/cyclestreets-core/build.gradle
libraries/cyclestreets-core/src/main/java/net/cyclestreets/AppInfo.java

After the latest beta came through to my phone, I noticed the About page looked like the following.  (The problem is the `local-build` string at the bottom.)
After the changes in the PR, I verified the fix in the emulator:
While I was at it, I also:
-  upgraded the versions of some dependencies
-  started adding release notes for the current version being developed.

Fix version code in About page

---

cyclestreets.app/src/main/assets/whatsnew.html
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/ElevationProfileFragment.java
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/ItineraryFragment.java
libraries/cyclestreets-fragments/src/main/res/layout/elevation_text.xml
libraries/cyclestreets-fragments/src/main/res/values-de/strings.xml
libraries/cyclestreets-fragments/src/main/res/values-es/strings.xml
libraries/cyclestreets-fragments/src/main/res/values-fr/strings.xml
libraries/cyclestreets-fragments/src/main/res/values-hi/strings.xml
libraries/cyclestreets-fragments/src/main/res/values-it/strings.xml
libraries/cyclestreets-fragments/src/main/res/values-mr/strings.xml
libraries/cyclestreets-fragments/src/main/res/values-pt/strings.xml
libraries/cyclestreets-fragments/src/main/res/values-ru/strings.xml
libraries/cyclestreets-fragments/src/main/res/values-tr/strings.xml
libraries/cyclestreets-fragments/src/main/res/values/strings.xml
libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/Elevation.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/ElevationFormatter.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/ElevationProfile.java

Closes #218.
In addition to the changes mentioned in that issue, I've also:
-  updated the itinerary overview to use Material style `textAppearance` as per the guide here: https://gist.github.com/webserveis/c8c7e001c617829caa61dae385113e00
-  changed the Imperial height display to be in feet, not yards (which I'm pretty sure is more usual).

Elevation / Itinerary improvements

---

libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/PhotoUploadFragment.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/TapToRouteOverlay.java

Closes #215.
A fairly simple change, in the end.
@jezhiggins a review please?

Move 'Share this Route' and 'Comment on this Route' items out of sub-menu

---

libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/RouteMapFragment.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/CycleMapView.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/ControllerOverlay.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/LocationOverlay.java

Closes #243.  For full description, see that issue.

Work around loss of location on save

---

libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/geojson/PoiFactory.java
libraries/cyclestreets-track/src/main/java/net/cyclestreets/track/SaveTrip.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/TapToRouteOverlay.java

Closes #186.
Also fixes a minor regression that erroneously transitioned our tap state to `ALL_DONE` without having done any routing, by clicking on the map when you already had the max number of waypoints.
@jezhiggins, can you please review?

Increase waypoint limit from 12 up to 30

---

build.gradle
cyclestreets.app/src/main/assets/whatsnew.html
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/addphoto/AddPhotoFragment.kt
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/iconics/IconicsHelper.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/ControllerOverlay.java

Described by each individual commit.

Minor fixes

---

libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/LiveRideService.kt

Fix LiveRide startup crash - last location may be null

---

libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/CycleMapFragment.kt
libraries/cyclestreets-track/src/main/java/net/cyclestreets/track/ShowJourney.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/CycleMapView.java

Closes #309.
We may want to evolve this solution at some point but this seems like a good starting point - if zoomed out, it zooms in to the point where street names first appear.

Minimum zoom for find place

---

libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/Journey.kt

Follows on from #322.
@mvl22 FYI

Use HTTPS for the cycle.st links we share

---

libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/AudioFocuser.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/LiveRideService.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/LiveRideState.kt
libraries/cyclestreets-view/src/test/java/net/cyclestreets/liveride/LiveRideVoiceTest.kt

Request audio focus for LiveRide directions

---

cyclestreets.app/build.gradle
cyclestreets.app/src/androidTest/java/net/cyclestreets/content/DatabaseUpgradeTest.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/content/DatabaseHelper.java

A weirdness that I noticed when trying to reproduce a separate issue.
This was pretty painful to figure out!
@jezhiggins can you review, please?

Fix DB upgrade test when running against Android 9 emulator

---

cyclestreets.app/src/main/java/net/cyclestreets/CycleStreets.kt
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/MainSupport.kt
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/SettingsFragment.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/tiles/TileSource.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/util/MapPack.java

Fix NPE in Settings fragment - check external storage permission before using it

---

libraries/cyclestreets-core/src/main/java/net/cyclestreets/util/AsyncDelete.kt
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/CycleMapFragment.kt
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/addphoto/AddPhotoFragment.kt
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/addphoto/Utils.kt

Delete asynchronously to reduce the probability of ANR hangs

---

libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/MainNavDrawerActivity.kt

Regression caused by #343.
I believe this may be a window condition on upgrading to the new version.
I don't want to lose the repro scenario from my phone, so I'm pushing a change through which I believe should fix things.

Fix NPE when hitting Back

---

build.gradle
libraries/cyclestreets-core/build.gradle
libraries/cyclestreets-core/src/test/java/net/cyclestreets/api/client/JourneyStringTransformerTest.java
libraries/cyclestreets-core/src/test/java/net/cyclestreets/api/client/RetrofitApiClientIntegrationTest.java
libraries/cyclestreets-core/src/test/java/net/cyclestreets/api/client/RetrofitApiClientTest.java
libraries/cyclestreets-fragments/build.gradle
libraries/cyclestreets-fragments/src/test/java/net/cyclestreets/MainSupportTest.kt
libraries/cyclestreets-view/build.gradle
libraries/cyclestreets-view/src/test/java/net/cyclestreets/liveride/LiveRideVoiceTest.kt
libraries/cyclestreets-view/src/test/java/net/cyclestreets/liveride/ReplanFromHereTest.kt

And reintroduce tests that we had to ignore previously.

Upgrade robolectric

---

build.gradle
libraries/cyclestreets-view/src/main/res/layout/compassbutton.xml

399: Fix LiveRide

---

.travis.yml
build.gradle
cyclestreets.app/build.gradle

... and related minor tweaks.
Not exciting, just some day-to-day housekeeping.

Upgrade to latest Android gradle plugin

---

libraries/cyclestreets-view/src/main/java/net/cyclestreets/util/EditTextHistory.java
libraries/cyclestreets-view/src/main/res/layout/texthistory.xml

Change textAppearance so items in list are now visible. 
Fixes #93

Check route number in list before adding to history for autocomplete.

---

.travis.yml
build.gradle

Upgrade target SDK, Android Gradle plugin, Kotlin etc

---

libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/LiveRideState.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/SpeechFixer.kt
libraries/cyclestreets-view/src/test/java/net/cyclestreets/liveride/SpeechFixerTest.kt

Fixes #442.
Nice and simple.  Review please 😄

442: add speech fixing for St Somebody Road

---

libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/RouteMapFragment.kt

To fix #466 (circular routes no longer working)

Changed distance/duration parms to null due to change at server end.

---

cyclestreets.app/build.gradle
cyclestreets.app/src/main/AndroidManifest.xml

Fix app startup crash

---

libraries/cyclestreets-view/src/main/java/net/cyclestreets/content/RouteData.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/content/RouteDatabase.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/CycleStreetsRoutingTask.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/LiveRideReplanRoutingTask.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/Route.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/RoutingTask.kt

Fixes #474 
[Test route saving for LiveRide replans.pdf](https://github.com/cyclestreets/android/files/6938622/Test.route.saving.for.LiveRide.replans.pdf)

Don't save LiveRide replans

---

libraries/cyclestreets-view/src/test/java/net/cyclestreets/liveride/LiveRideVoiceTest.kt
libraries/cyclestreets-view/src/test/java/net/cyclestreets/liveride/ReplanFromHereTest.kt

Add saveRoute parm to tests

---

libraries/cyclestreets-view/src/main/java/net/cyclestreets/util/Brush.java
libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/WaymarkOverlay.kt

To fix #317 
See what you think about the size, if you want to check it on your phone.  If it's too small, can always increase to 1.8.

Increase waymark size and add waymark number.

---

cyclestreets.app/src/main/assets/whatsnew.html
cyclestreets.app/src/main/play/release-notes/en-GB/beta.txt

Fixes #506 
Do I need to change whatsnew.html to match?  Or can I leave it in the wordier form?

Shortened beta.txt

---

.travis.yml
build.gradle
ciPublish.sh
cyclestreets.app/build.gradle
cyclestreets.app/src/main/AndroidManifest.xml
gradle.properties
gradle/wrapper/gradle-wrapper.properties
libraries/cyclestreets-core/build.gradle
libraries/cyclestreets-core/src/main/AndroidManifest.xml
libraries/cyclestreets-fragments/build.gradle
libraries/cyclestreets-fragments/src/main/AndroidManifest.xml
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/CycleMapFragment.kt
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/SettingsFragment.kt
libraries/cyclestreets-view/build.gradle
libraries/cyclestreets-view/src/main/AndroidManifest.xml
libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/RouteHighlightOverlay.kt

Having just moved to SDK level 31, we're already being pushed to target 33. 
Might as well try and update everything else - gradle, kotlin, dependencies, etc - while we're at it and get everything done in one fell swoop.

Target API 33

---

README.md
cyclestreets.app/src/main/assets/credits.html

Bump copyright date to 2024. 

---

.travis.yml
build.gradle
libraries/cyclestreets-core/build.gradle
libraries/cyclestreets-core/src/main/java/net/cyclestreets/util/AsyncDelete.kt
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/CycleMapFragment.kt
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/LocationsFragment.kt
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/MainNavDrawerActivity.kt
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/RouteMapFragment.kt
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/SettingsFragment.kt
libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/addphoto/AddPhotoFragment.kt
libraries/cyclestreets-view/build.gradle
libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/LiveRideService.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/photos/FetchIndividualPhotoTask.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/CycleStreetsRoutingTask.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/FetchCycleStreetsRouteTask.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/LiveRideReplanRoutingTask.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/ReplanRoutingTask.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/RoutingTask.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/StoredRoutingTask.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/POIOverlay.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/place/AsyncContactLoad.kt
libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/place/AsyncContactLookup.kt

Bump all the dependencies to their latest versions

Dependencies update

---

.travis.yml
cyclestreets.app/build.gradle
cyclestreets.app/src/main/AndroidManifest.xml
libraries/cyclestreets-view/src/main/AndroidManifest.xml

liveride crashing following recent update
