cyclestreets.vNext/build.gradle, libraries/cyclestreets-core/build.gradle, libraries/cyclestreets-fragments/build.gradle, libraries/cyclestreets-view/build.gradle
-  Upgrade minor/patch versions of dependencies
-  While we're at it, fix alignment and conform with convention (as I understand it!) for Gradle dependency definition layout.
Note that `org.osmdroid:osmdroid-android:4.3' has a major upgrade available of `5.2`.  I haven't changed that in this PR as there are associated API changes.
=> Upgrade minor/patch versions of dependencies

libraries/cyclestreets-core/build.gradle, libraries/cyclestreets-view/src/main/java/net/cyclestreets/tiles/CycleMapTileProvider.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/tiles/TileSource.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/tiles/UserAgentInterceptor.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/util/ImageDownloader.java, libraries/cyclestreets-view/src/main/java/org/mapsforge/android/maps/MapsforgeOSMDroidTileProvider.java, libraries/cyclestreets-view/src/main/java/org/osmdroid/tileprovider/modules/CycleStreetsTileDownloader.java
As discussed previously, before we can migrate to the latest osmdroid library, and generally for getting our app up-to-date, we need to remove the remaining usages of `org.apache.http.*` classes.  These existed in the following places:
1.  `TileSource` - to initialise the `HttpClientFactory` to set the `http.useragent` to be `AppInfo.version()`
2.  `ImageDownloader` - for downloading CycleStreets images, using the `thumbnailUrl` field returned from the `photomap.locations` API.
3.  `CycleStreetsTileDownloader` and `MapsforgeOSMDroidTileProvider` - for getting map tiles (I haven't worked out what the differences between these are; my guess is one would use the downloadable map pack, but @mvl22 @jezhiggins I'd welcome some more background info on this).
My thought processes went like this: …
=> Migrate remaining usages of Apache HttpClient

libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/ApiClient.java
The following three bugs have been fixed.  They're all rather silly.
-  Hostnames passed to Retrofit need the scheme to be included.
-  Retrofit needs the context to determine its cache dir.
-  Don't attempt to use Retrofit before it's been initialised.
Now that these changes have been made, the app starts up once again when I tested it locally.
Apologies for breaking the builds; I'll endeavour to make sure it doesn't happen again!
=> Fix three silly bugs

cyclestreets.vNext/build.gradle, cyclestreets.vNext/src/androidTest/java/net/cyclestreets/AppStartupTest.java, libraries/cyclestreets-core/build.gradle, libraries/cyclestreets-view/build.gradle
See https://google.github.io/android-testing-support-library/docs/espresso/index.html for details of Espresso.  It's the framework that was generally recommended by the helpful folks in the Android development community of practice where I work.
With these changes, **and either an emulator running or a real Android device connected**, you can run `./gradlew cyclestreets.vNext:connectedCheck`.  I have proved that this a valid test for app startup, since we know `master` is currently broken, and the test fails with just the changes in this PR, but passes once the bug fixes in #147 are merged in.
I propose getting this PR (and for that matter #147!) in as-is.  Subsequently we can look at automating the creation, starting and stopping of an emulator on CI and/or local builds, so that this …
=> Add basic app startup tests using Espresso

cyclestreets.vNext/src/main/assets/credits.html, libraries/cyclestreets-core/build.gradle, libraries/cyclestreets-core/src/main/java/net/cyclestreets/AppInfo.java
In conjunction with changes I intend to make to our Jenkins build, this addresses #159.
Local builds, created on a developer machine, will appear along the lines of `net.cyclestreets/3.4/local-build`:
Proper CI builds will appear along the lines of `net.cyclestreets/3.4/2016-10-11-0045`.
=> Include build identifier in version on About page

libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/RewriteCacheControlInterceptor.java, libraries/cyclestreets-core/src/test/java/net/cyclestreets/api/client/RetrofitApiClientTest.java
As discussed in #144 we can now remove some of this workaround logic.
=> Remove workaround for endpoints that now return valid Cache-Control headers

.travis.yml
Much to my disappointment, I've been unable to get the connected Android tests (using an emulator) to run reliably on Travis.
We need the builds to run on Travis as that's how we're publishing updated betas (which could of course then be release candidates.
Therefore this PR removes the relevant parts of `.travis.yml`.  I'll check back at some point in a few months and see if Travis have improved things in this regard, at which point I can refer back to this delta as a starting point.
In the meantime, whenever we have PRs reviewed and ready to merge, I'll take the action of running the emulator tests locally.
=> Disable emulator-based tests on Travis, due to instability

.travis.yml, build.gradle, cyclestreets.app/version.properties
Connects to #179.
The Play store APIs only accept an APK submission if the versionCode (an integer) has not already been used. You can see an example failure here:
>```
>:cyclestreets.app:publishApkRelease FAILED
>FAILURE: Build failed with an exception.
>* What went wrong:
>Execution failed for task ':cyclestreets.app:publishApkRelease'.
>> com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
>  {
>    "code" : 403,
>    "errors" : [ {
>      "domain" : "androidpublisher",
>      "message" : "APK specifies a version code that has already been used.",
>      "reason" : "apkUpgradeVersionConflict"
>    } ],
>    "message" : "APK specifies a version code that has already been used."
>  }
>```
Therefore, versionCode has to be monotonically increasing.
The most …
=> Use number of commits on branch as the version code

libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/CycleMapView.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/LocationOverlay.java
Closes #89.
Screenshots show the maximum and minimum zoom levels now supported, which I think are not unreasonable.
Note that while I was dealing with this trivial change, I fixed up the follow-me button "on" highlighting to be clear again, which had been regressed.
=> Set maximum and minimum zoom levels to more sensible values

libraries/cyclestreets-core/build.gradle, libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/JourneyStringTransformer.kt, libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/RetrofitApiClient.java, libraries/cyclestreets-core/src/test/java/net/cyclestreets/api/client/JourneyStringTransformerTest.java, libraries/cyclestreets-core/src/test/resources/__files/journey-v1api-single-segment.json, libraries/cyclestreets-core/src/test/resources/__files/journey-v1api-single-segment.xml, libraries/cyclestreets-core/src/test/resources/journey-single-segment-domain.json, libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/Journey.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/Route.java
Closes #298.
This PR also
-  improves the logging we do around route finding failures
-  introduces OkHttp's `HttpLoggingInterceptor`, but leaves it disabled by default since at the moment there doesn't seem to be a way to stop it from logging the API key, which I'd rather not do (see https://github.com/square/okhttp/issues/4244).
=> Fix route finding failures for single-segment routes

libraries/cyclestreets-core/build.gradle, libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/ApiClient.kt, libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/HttpLoggingInterceptor.kt, libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/RetrofitApiClient.java, libraries/cyclestreets-core/src/main/java/net/cyclestreets/util/Logging.java
Adding in a custom logging interceptor so we don't log the API key.
Also fixing a recursion bug accidentally introduced by a previous PR - my bad.
=> Fix recursion bug; add a logging interceptor

libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/ApiClient.kt, libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/GeoPlaces.java, libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/Photos.java
PR #293 refactored the API client.
This introduced a bug, because the arguments for various APIs (west, south, east, north) were ordered inconsistently.
This PR fixes that bug and makes the argument ordering consistent across the API and its use cases, in a way that matches the underlying API itself.
(Bug was spotted while gathering screenshots for #257.)
=> Fix regression (no photos in photomap!) caused by inconsistent argument ordering

libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/LockScreenOnOverlay.java, libraries/cyclestreets-view/src/main/res/values/strings.xml
Relates to discussions in #42 and #303.
This PR does not change the images that are used (since we have yet to come to an agreement around that) but it does add an explanatory message (slightly tweaked from @si-the-pie's original suggestions).  It also fixes the you-need-to-click-twice-the-first-time issue.
I hope this is sufficient for the 3.6 release.
@si-the-pie @mvl22 when you've discussed between yourselves and agreed what the icons should be for the subsequent 3.7 release, please raise a new issue accordingly (or just a PR - it should be pretty obvious what the trivial changes would be to adjust which icons are chosen).
=> Explanatory messages for Live Ride screen lock button

cyclestreets.app/src/main/AndroidManifest.xml, libraries/cyclestreets-fragments/src/test/java/net/cyclestreets/MainSupportTest.kt
Addresses @mvl22's post-merge comment https://github.com/cyclestreets/android/commit/f0441828cdef6d23d2436459e08f07d375103477#commitcomment-30390774 following PR #319
>Just to flag up that cycle.st is about to get HTTPS at last - for some reason this was accidentally missed when we shifted our infrastructure to HTTPS. So please do include this in the list of intents.
=> Allow HTTPS intents for cycle.st URLs

libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/MainNavDrawerActivity.kt
Closes #342.
This change means that:
-  some fragments can be backed out of
-  not all fragments are restored on pause/resume.
See inline comments for full details.
=> Adjust fragment navigation behaviour ("Back" button, etc.)

libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/Blog.java, libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/BlogFragment.kt
Prevents the redirect, so we stay with the app.
Fixes #295, specifically https://github.com/cyclestreets/android/issues/295#issuecomment-616092298
=> 295: Point Blog URL to cyclestreets.org/news

cyclestreets.app/src/main/assets/whatsnew.html, libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/MainNavDrawerActivity.kt, libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/SettingsFragment.kt
Making Back button behaviour more straightforward.
Rather than trying to maintain the backstack through all the navigation menu changes (which isn't like behaviour of eg gmail or twitter), aiming for
* if you're on the journey planner, back leaves the app
* if you're not on the journey planner, back should take you to the journey planner
* unless you're part way through adding a photo, in which case back takes you to the previous step
* or you're on a setting subscreen, in which case back return you to settings
* or you're on the journey planner and planning a route, in which case back removes the most recent waypoint wisp
Fixes #368, will hopefully also address #364.
=> Rework Back button behaviour

cyclestreets.app/src/main/assets/whatsnew.html, libraries/cyclestreets-core/build.gradle, libraries/cyclestreets-track/src/main/java/net/cyclestreets/track/JourneyOverlay.java, libraries/cyclestreets-track/src/main/java/net/cyclestreets/track/RecordingService.java, libraries/cyclestreets-track/src/main/java/net/cyclestreets/track/ShowJourney.java, libraries/cyclestreets-track/src/main/java/net/cyclestreets/track/TripData.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/Segment.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/tiles/UpsizingTileSource.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/CycleMapView.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/LiveItemOverlay.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/RouteOverlay.java, libraries/cyclestreets-view/src/main/java/org/mapsforge/map/android/MapsforgeOSMDroidTileProvider.java, libraries/cyclestreets-view/src/main/java/org/mapsforge/map/android/MapsforgeOSMTileSource.java, libraries/cyclestreets-view/src/main/java/org/osmdroid/tileprovider/modules/CycleStreetsTileDownloader.java
This PR:
-  upgrades `osmdroid` to the current latest (from `5.6.5` to `6.0.3`)
-  handles the necessary API changes
-  in addition, limits the north/south (latitude) scrollability of the map to the range [-80, 80] degrees.  (This ability was introduced in version `6.0.0` and is the main reason I did the upgrade at this point.)
To give a little more context on the last point:
-  previously, you could keep scrolling north/south beyond what's logical (e.g. go beyond Antarctica to Greenland) as many times as you like
-  I initially limited the scrollability to the absolute poles (as per https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java#L741-L759)
-  There was still a lot of "blank space" and I can't believe there's any meaningful …
=> Upgrade osmdroid; restrict max/min latitude

RELEASING.md, cyclestreets.app/src/main/play/release-notes/en-GB/production.txt
In my view we're in a good state to get 3.7 out the door.  Once this is approved and merged, I'll perform the remaining steps to get this done.
=> Prepare release notes for launching version 3.7

libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/Route.kt
It's possible that the stashed waypoints string might be empty, rather
that null. In this case, attempting to restore waypoints at app start
will throw a number format exception and the app will crash.
This patch corrects that.
=> Fix NumberFormatException in Route.restoreWaypoints

cyclestreets.app/src/main/assets/whatsnew.html, cyclestreets.app/src/main/play/release-notes/en-GB/beta.txt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/LocationOverlay.kt
When locked on location, ignore single-finger pan events. Allow
multitouch through, so the gesture detector can pick up pinch-zoom
properly.
You do get a little bit of panning during a pinch-zoom (and also
double-tap zoom), but the next location update will recentre the map.
Fixes #384.
=> Fix pinch-zoom in LiveRide

cyclestreets.app/src/main/assets/whatsnew.html, cyclestreets.app/src/main/play/release-notes/en-GB/beta.txt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/LiveRideState.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/SpeechFixer.kt, libraries/cyclestreets-view/src/test/java/net/cyclestreets/liveride/SpeechFixerTest.kt
Towards issue #393.
(doesn't close it, because there's still some open discussion about how to handle road numbers).
=> 393: fix pronounciation of metres and kilometres

cyclestreets.app/src/main/assets/whatsnew.html, cyclestreets.app/src/main/play/release-notes/en-GB/beta.txt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/SpeechFixer.kt, libraries/cyclestreets-view/src/test/java/net/cyclestreets/liveride/SpeechFixerTest.kt
Closes #393.
I have tested this in the emulator and it sounds good to me in the cases I tried.
If anyone's interested, hyphens don't work, because it sometimes reads them out as "minus" 😂
=> 393: Fix how 3/4-digit road numbers are pronounced in LiveRide

build.gradle, libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/LocationsFragment.kt
Closes #404.
The Javadoc for this parameter explicitly says:
> You should check that this view is non-null and of an appropriate type before using.
So it's just an artifact of the migration to Kotlin that this is failing.  (Because we haven't got round to making this stuff as finely tuned as it could be, we don't even use this parameter, so the crash is entirely unnecessary...!)
=> 404: classic Kotlin parameter nullability bug

libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/MainNavDrawerActivity.kt
It appears that on upgrade we don't always get a sensible selectedItem
value back in MainNavDrawerActivity.onResume. In this case, if showPage
fails, call it again specifying the journay planner.
=> If we don't restore to a page, force to the journey planner

cyclestreets.app/src/main/assets/whatsnew.html, cyclestreets.app/src/main/play/release-notes/en-GB/beta.txt, libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/CycleMapFragment.kt, libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/RouteMapFragment.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/CycleMapView.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/ControllerOverlay.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/FindPlaceOverlay.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/LiveItemOverlay.java
Fixes #428 
I used the "There" marker from the location editor (the red cross) for the Find Place marker.
Tested the following (see attached pdf for more detail):
Journey Planner
Photo map
Move screen
Zoom in and out
Combine with POI's, Waymarks, route highlight, location, various combinations
Back button (for the various combinations above)
Follow location
[Test FInd Place marker 200721.pdf](https://github.com/cyclestreets/android/files/4956019/Test.FInd.Place.marker.200721.pdf)
Screenshot with the marker:
=> Add overlay to mark Find Place on map

libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/SettingsFragment.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/tiles/TileSource.java, libraries/cyclestreets-view/src/main/res/xml/prefs.xml
Closes #436.
It's causing crashes on some phones, and will be replaced with a new
mechanism soon, see PR #417.
=> Rip out vector mapfile setting

libraries/cyclestreets-core/src/main/java/net/cyclestreets/CycleStreetsPreferences.java, libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/CycleMapFragment.kt, libraries/cyclestreets-view/src/main/AndroidManifest.xml, libraries/cyclestreets-view/src/main/java/net/cyclestreets/util/Permissions.kt, libraries/cyclestreets-view/src/main/res/values/strings.xml
Closes #429, #411.
Supercedes #438.
The idea of this is to:
- take what @HilaryN figured out in #438 and apply that (the first commit)
- improve the "justification" screens that give context for why we're asking for permissions, by:
- making the text clearer and more thorough
- always including them (including before first attempt to request, unlike previously)
- if the user has clicked "Deny" and "Never ask again" then actions which require a given permission should now give an updated justification message, and then take the user to the app settings screen directly, from where they have an opportunity to grant the permission (previously, in this scenario no justification would be seen and no opportunity to change permissions would be given, meaning the functionality - e.g. clicking …
=> Fix permissions for LiveRide, and generally improve how we request permissions.

.travis.yml, build.gradle, cyclestreets.app/build.gradle, libraries/cyclestreets-core/build.gradle, libraries/cyclestreets-fragments/build.gradle, libraries/cyclestreets-view/build.gradle, libraries/cyclestreets-view/src/test/java/net/cyclestreets/liveride/ReplanFromHereTest.kt
Based on https://developer.android.com/about/versions/11/behavior-changes-all I think this should be fine (we've already improved our approach around permissions in a relevant way).
Based on https://developer.android.com/about/versions/11/behavior-changes-11 I am **not** yet upgrading the target SDK - since I think the statement of:
> Scoped storage enforcement: Access into external storage directories is limited to an app-specific directory and specific types of media that the app has created.
has a potential impact until Jez's work on the offline mapping download has been completed.
@jezhiggins @mvl22 @HilaryN please review.
=> Update compile SDK from 29 (Android 10) to 30 (Android 11)

build.gradle
Things seems to work OK in the emulator (both Android 10 and Android 11) with these changes in place.
Closes #445.
=> 445: upgrade target SDK to 30 (Android 11)

build.gradle, cyclestreets.app/build.gradle, cyclestreets.app/src/main/assets/whatsnew.html, cyclestreets.app/src/main/play/release-notes/en-GB/beta.txt, cyclestreets.app/src/main/play/release-notes/en-GB/production.txt, libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/CycleStreetsAppSupport.java
Fixes #461.
I've tested this works locally, on my real phone, reproducing and fixing as follows: (relevant logs inlined for each stage)
- installing 3.8.1 fresh
```
I/views.CycleMapView: Creating map view. App has write-external permission? false; osmdroid base path: /data/user/0/net.cyclestreets/files/osmdroid; osmdroid tile cache location: /data/user/0/net.cyclestreets/files/osmdroid/tiles
```
- approving permissions
```
I/views.CycleMapView: Creating map view. App has write-external permission? true; osmdroid base path: /storage/emulated/0/osmdroid; osmdroid tile cache location: /storage/emulated/0/osmdroid/tiles
```
- upgrading to 3.9, map tile downloads stop working
```
I/views.CycleMapView: Creating map view. App has write-external permission? true; osmdroid base path: …
```
=> 461: fix tile loading regression bug

libraries/cyclestreets-view/build.gradle
I've not had chance to look into this, so maybe revert to 5.0.3 for now?
Fixes #471
=> Revert to mikepenz iconics 5.0.3 as icons disappear with 5.2.8

libraries/cyclestreets-view/build.gradle, libraries/cyclestreets-view/src/main/java/net/cyclestreets/content/RouteData.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/ReplanFromHere.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/Route.kt, libraries/cyclestreets-view/src/test/java/net/cyclestreets/liveride/ReplanFromHereTest.kt
Fixes #476 
[Test LiveRide replan uses current plan.pdf](https://github.com/cyclestreets/android/files/6940526/Test.LiveRide.replan.uses.current.plan.pdf)
=> Use current journey plan for LiveRide replans

libraries/cyclestreets-core/src/main/java/net/cyclestreets/CycleStreetsPreferences.java, libraries/cyclestreets-view/src/main/java/net/cyclestreets/AccountDetailsActivity.java
Hello developers of CycleStreets
I am using your app CycleStreets. I think the app is great but I have one minor patch that could improve the user experience.
Here are some pictures to help illustrate my patch: https://imgur.com/a/S7iCRWB
In picture 1, a user has partially filed out his registration information. If something like a phone call moves the screen to another activity or if the user accidentally closes the app or presses back. The app should preserve the data in this case. However, once the user returns he will lose information he had filed in so far. This can be seen in pictures 1 and 2. Our patch will preserve this data so there will be no data loss in situations like this.
Another issue is when the user finishes registration. When the user wants to register another account. …
=> patch(data loss) 1

libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/Bubble.kt
Fixes #508 
Tested on Pixel 4 API 30 (Android 11), Nexus 6 API 29 (Android 10) to check POI link worked, and my own phone, Fairphone 3, Android 11, to check app selector came up.
=> POI link fixed for Android 11

libraries/cyclestreets-core/src/test/java/net/cyclestreets/api/client/RetrofitApiClientTest.java
Failing test after redoing the icons.  It looks like the one icon the test relied on is one that's been removed. :roll_eyes:
=> Correct POI test now the icons have been fixed up

.travis.yml, build.gradle, cyclestreets.app/build.gradle, cyclestreets.app/src/main/AndroidManifest.xml, gradle/wrapper/gradle-wrapper.properties, libraries/cyclestreets-view/build.gradle
Move to Target 31 finally built green, but then the publish step fell over. 
So, we've got to bump to Java 11, and that's triggered it's own series of cascading changes :roll_eyes:
=> Bump java version

cyclestreets.app/build.gradle, libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/LiveRideState.kt
This was a breaking change in the enforced move to the new API level. I don't think there was a build warning for it (although having identified the problem, the IDE has a squigly under the offending line). Even if there was I would have missed it in all the deprecation warnings to which we are now subject.
=> Add PendingIntent.FLAG_IMMUTABLE

libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/AdvanceToSegment.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/Arrivee.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/GoingOffCourse.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/LiveRideStart.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/LiveRideState.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/NearingTurn.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/PassingWaypoint.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/liveride/ReplanFromHere.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/ControllerOverlay.java, libraries/cyclestreets-view/src/test/java/net/cyclestreets/liveride/LiveRideVoiceTest.kt
Allows voice instructions to be canceled halfway through speaking to allow more accurate voice instructions.
On a subsequent call of the speak() method, the queue of voice instructions is completely cleared.
=> changed speak() to cancel any voice instructions already queued

cyclestreets.app/src/main/play/release-notes/en-GB/beta.txt, libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/CycleMapFragment.kt, libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/addphoto/AddPhotoFragment.kt, libraries/cyclestreets-view/src/main/AndroidManifest.xml, libraries/cyclestreets-view/src/main/java/net/cyclestreets/util/Permissions.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/CycleMapView.java, libraries/cyclestreets-view/src/main/res/values/strings.xml
To fix #542 
I haven't touched the READ permission request in MapPack as I think that isn't working at the moment?  
Write permissions for app-specific storage (i.e. map tiles) is no longer required.  Same for Read permission for app-specific storage (which doesn't seem to get explicitly requested, presumably as it's granted as part of the write permission).  Removed for Android 13 upwards. (CycleMapFragment)
Note that because permission for map tiles is no longer granted, the old cache location won't get removed – I'm not sure if this is an issue?  (See CycleMapFragment.onRequestPermissionsResult)
CycleMapView – I've just changed the log message in here.
Write permission to store photos should be handled by the camera app – removed for Android 13 upwards. (AddPhotoFragment)
Read …
=> 542 write external storage deprecated

libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/CycleStreetsAppSupport.java
This is relatively drastic, but we've got a number of reports where the app stops drawing tiles when the phone OS has been upgraded. We don't currently detect that situation (which can require a cahce reset), but if we try this on our beta channel we can at least get an idea if it'll help.
If yes, we can do it properly. Otherwise we can roll back.
=> Resetting the OSMDroid tile cache.

cyclestreets.app/src/main/assets/whatsnew.html, cyclestreets.app/src/main/play/release-notes/en-GB/beta.txt, libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/POI.java, libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/dto/PoiTypesDto.kt, libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/geojson/PoiFactory.java, libraries/cyclestreets-core/src/test/java/net/cyclestreets/api/client/RetrofitApiClientTest.java, libraries/cyclestreets-core/src/test/resources/__files/pois.json, libraries/cyclestreets-view/src/main/java/net/cyclestreets/routing/Journey.kt, libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/POIOverlay.kt
To fix #554 
This works, but I'm not sure it's a robust solution as I removed the hashCode override.
@mvl22  is the number within the POI ID unique?  Or perhaps unique within category?
=> Changed POI id to String and removed hashCode.

build.gradle, cyclestreets.app/build.gradle, cyclestreets.app/src/androidTest/java/net/cyclestreets/content/DatabaseUpgradeTest.java, cyclestreets.app/src/main/assets/whatsnew.html, cyclestreets.app/src/main/play/release-notes/en-GB/beta.txt, cyclestreets.app/src/main/play/release-notes/en-GB/production.txt, gradle/wrapper/gradle-wrapper.properties, libraries/cyclestreets-core/build.gradle
Our mandated move to targetting SDK level 34, and the associated tools and library bumps. 
Closes #557
=> DRAFT: Target SDK Level 34, move to AGP 8.2.2, Kotlin 1.9,20

cyclestreets.app/build.gradle
We need to edit the declared permissions, so we need to create the new release as a draft. 
I don't think I have the signing keys any more, so need to get the Travis build to create the artifact, upload it, but not try to push it out. Once that's done, I can update the permissions in the Play Console, revert this change, and, hopefully we can all relax again until we get pushed into this upgrade dance again this time next year.
=> Draft rather than publish new release
